# Project definition for the default project
apiVersion: openchoreo.dev/v1alpha1
kind: Project
metadata:
  name: default
spec:
  displayName: "Default Project"
  description: "Default project for warehouse inventory demo"
