apiVersion: openchoreo.dev/v1alpha1
kind: DeploymentPipeline
metadata:
  name: simple-pipeline
  namespace: default
spec:
  promotionPaths:
    - sourceEnvironmentRef: development
      targetEnvironmentRefs: []
