# Component definition for inventory-api-gitops
# The Workload, ComponentRelease, and ReleaseBinding will be added by GitOps workflow
apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: inventory-api-gitops
spec:
  projectRef: default
  displayName: "Inventory API (GitOps)"
  description: "Go backend API for warehouse inventory - deployed via GitOps"
